/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.menus;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import login.Login;
import login.usersLogin;
import raven.table.Test;
import sql.crudsql;
import vistas.ingresar.IngresarProducto;

/**
 *
 * @author Jess
 */
public class MenuPrincipal extends javax.swing.JFrame {
    
    usersLogin user = new usersLogin();
    crudsql crud=new crudsql();
    Test tablita = new Test();
    IngresarProducto ad = new IngresarProducto();

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        buscar.setBackground(Color.WHITE);
        buscar.setFocusable(false); 
       
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Pstocks = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        signout4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Ptables = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        ico3 = new javax.swing.JLabel();
        Pfiles = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Pitems = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        ico2 = new javax.swing.JLabel();
        Panelmenu = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        signOut = new javax.swing.JLabel();
        help = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JTextField();
        add = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        signOut4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(-2, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(844, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(42, 33, 133));
        Titulo.setText("Available inventory");
        Titulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Titulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TituloMouseClicked(evt);
            }
        });
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 280, 50));

        Pstocks.setBackground(new java.awt.Color(255, 255, 255));
        Pstocks.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        Pstocks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pstocks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PstocksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PstocksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PstocksMouseExited(evt);
            }
        });
        Pstocks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Stock Items");
        Pstocks.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        signout4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        signout4.setForeground(new java.awt.Color(42, 33, 133));
        signout4.setText("5");
        signout4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signout4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signout4MouseClicked(evt);
            }
        });
        Pstocks.add(signout4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/alert.png"))); // NOI18N
        Pstocks.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 60));

        jPanel1.add(Pstocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 220, 120));

        Ptables.setBackground(new java.awt.Color(255, 255, 255));
        Ptables.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        Ptables.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ptables.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PtablesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PtablesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PtablesMouseExited(evt);
            }
        });
        Ptables.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        l1.setForeground(new java.awt.Color(42, 33, 133));
        l1.setText("001");
        l1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        Ptables.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 70));

        l2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(153, 153, 153));
        l2.setText("Tables");
        Ptables.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        ico3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cells.png"))); // NOI18N
        Ptables.add(ico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 60));

        jPanel1.add(Ptables, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 220, 120));

        Pfiles.setBackground(new java.awt.Color(255, 255, 255));
        Pfiles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        Pfiles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pfiles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PfilesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PfilesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PfilesMouseExited(evt);
            }
        });
        Pfiles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("File");
        Pfiles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/file.png"))); // NOI18N
        Pfiles.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 60));

        jPanel1.add(Pfiles, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 220, 120));

        Pitems.setBackground(new java.awt.Color(255, 255, 255));
        Pitems.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        Pitems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Pitems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PitemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PitemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PitemsMouseExited(evt);
            }
        });
        Pitems.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        l3.setForeground(new java.awt.Color(42, 33, 133));
        l3.setText("120");
        l3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        Pitems.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 70));

        l4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(153, 153, 153));
        l4.setText("Items");
        Pitems.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        ico2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/prenda.png"))); // NOI18N
        Pitems.add(ico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 70, 60));

        jPanel1.add(Pitems, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 220, 120));

        Panelmenu.setBackground(new java.awt.Color(42, 33, 133));
        Panelmenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panelmenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 290, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("StockFlow");
        Panelmenu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        signOut.setBackground(new java.awt.Color(42, 33, 133));
        signOut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        signOut.setForeground(new java.awt.Color(255, 255, 255));
        signOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ingresar.png"))); // NOI18N
        signOut.setText("  Sign out");
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut.setOpaque(true);
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOutMouseExited(evt);
            }
        });
        Panelmenu.add(signOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 230, 410, 40));

        help.setBackground(new java.awt.Color(42, 33, 133));
        help.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        help.setForeground(new java.awt.Color(255, 255, 255));
        help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/help.png"))); // NOI18N
        help.setText("  Help");
        help.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        help.setOpaque(true);
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpMouseExited(evt);
            }
        });
        Panelmenu.add(help, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 130, 420, 40));

        setting.setBackground(new java.awt.Color(42, 33, 133));
        setting.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        setting.setForeground(new java.awt.Color(255, 255, 255));
        setting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/settings.png"))); // NOI18N
        setting.setText("  Settings");
        setting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setting.setOpaque(true);
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });
        Panelmenu.add(setting, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 180, 410, 40));

        home.setBackground(new java.awt.Color(42, 33, 133));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        home.setText("  Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setOpaque(true);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        Panelmenu.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 80, 410, 40));

        jPanel1.add(Panelmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 330, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/lupa.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, 20, 20));

        buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buscar.setForeground(new java.awt.Color(102, 102, 102));
        buscar.setText("Search here");
        buscar.setBorder(null);
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarMousePressed(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 270, 20));

        add.setBackground(new java.awt.Color(255, 255, 255));
        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        add.setText("Delete");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setOpaque(true);
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 230, 30, -1));

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setOpaque(true);
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 230, 30, -1));

        signOut4.setBackground(new java.awt.Color(255, 255, 255));
        signOut4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signOut4.setForeground(new java.awt.Color(255, 255, 255));
        signOut4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signOut4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/refresh.png"))); // NOI18N
        signOut4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOut4.setOpaque(true);
        signOut4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signOut4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signOut4MouseExited(evt);
            }
        });
        jPanel1.add(signOut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, 30, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMousePressed
        if(buscar.getText().equals("Search here"))
        buscar.setText("");
        buscar.setFocusable(true);
        buscar.requestFocusInWindow();
    }//GEN-LAST:event_buscarMousePressed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarActionPerformed

    private void signout4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signout4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signout4MouseClicked

    private void signOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseEntered
        signOut.setBackground(new java.awt.Color(255,255,255));
        signOut.setForeground(new java.awt.Color(42,33,133));
    }//GEN-LAST:event_signOutMouseEntered

    private void signOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseExited
        signOut.setBackground(new java.awt.Color(42,33,133));
        signOut.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_signOutMouseExited

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setBackground(new java.awt.Color(255,255,255));
        home.setForeground(new java.awt.Color(42,33,133));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setBackground(new java.awt.Color(42,33,133));
        home.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_homeMouseExited

    private void helpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseEntered
        help.setBackground(new java.awt.Color(255,255,255));
        help.setForeground(new java.awt.Color(42,33,133));
    }//GEN-LAST:event_helpMouseEntered

    private void helpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseExited
        help.setBackground(new java.awt.Color(42,33,133));
        help.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_helpMouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        setting.setBackground(new java.awt.Color(255,255,255));
        setting.setForeground(new java.awt.Color(42,33,133));
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited
        setting.setBackground(new java.awt.Color(42,33,133));
        setting.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_settingMouseExited

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l3MouseClicked

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_l1MouseClicked

    private void PtablesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtablesMouseClicked
        System.out.println("boton tablas");
        tablita.testData();
        tablita.setVisible(true);
        tablita.setBounds(330, 300, 872, 418);
       
    }//GEN-LAST:event_PtablesMouseClicked

    private void PtablesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtablesMouseExited
        Ptables.setBackground(new java.awt.Color(255,255,255));
        l1.setForeground(new java.awt.Color(42,33,133));
        l2.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_PtablesMouseExited

    private void PtablesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PtablesMouseEntered
        Ptables.setBackground(new java.awt.Color(42,33,133));
        l1.setForeground(new java.awt.Color(255,255,255));
        l2.setForeground(new java.awt.Color(255,255,255));
        
    }//GEN-LAST:event_PtablesMouseEntered

    private void PitemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PitemsMouseClicked
        
    }//GEN-LAST:event_PitemsMouseClicked

    private void PitemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PitemsMouseEntered
        Pitems.setBackground(new java.awt.Color(42,33,133));
        l3.setForeground(new java.awt.Color(255,255,255));
        l4.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PitemsMouseEntered

    private void PitemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PitemsMouseExited
        Pitems.setBackground(new java.awt.Color(255,255,255));
        l3.setForeground(new java.awt.Color(42,33,133));
        l4.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_PitemsMouseExited

    private void PfilesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PfilesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PfilesMouseClicked

    private void PfilesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PfilesMouseEntered
        Pfiles.setBackground(new java.awt.Color(42,33,133));
        jLabel12.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PfilesMouseEntered

    private void PfilesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PfilesMouseExited
        Pfiles.setBackground(new java.awt.Color(255,255,255));
        jLabel12.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_PfilesMouseExited

    private void PstocksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PstocksMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_PstocksMouseClicked

    private void PstocksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PstocksMouseEntered
        Pstocks.setBackground(new java.awt.Color(42,33,133));
        signout4.setForeground(new java.awt.Color(255,255,255));
        jLabel15.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_PstocksMouseEntered

    private void PstocksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PstocksMouseExited
        Pstocks.setBackground(new java.awt.Color(255,255,255));
        signout4.setForeground(new java.awt.Color(42,33,133));
        jLabel15.setForeground(new java.awt.Color(153,153,153));
    }//GEN-LAST:event_PstocksMouseExited

    private void TituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void deleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseEntered

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseExited

    private void signOut4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOut4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_signOut4MouseEntered

    private void signOut4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOut4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_signOut4MouseExited

    private void signOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMouseClicked
        Login lo = new Login();
        lo.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_signOutMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        System.out.println("Se presionó el botón eliminar");
        tablita.eliminarFila();
        tablita.testData();
        tablita.setVisible(true);

        

    }//GEN-LAST:event_deleteMouseClicked

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        System.out.println("add");
        ad.setVisible(true);
        tablita.setVisible(false);
        
        
        
       
    }//GEN-LAST:event_addMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        FlatLaf.registerCustomDefaultsSource("raven.table");
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
                
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelmenu;
    private javax.swing.JPanel Pfiles;
    private javax.swing.JPanel Pitems;
    private javax.swing.JPanel Pstocks;
    private javax.swing.JPanel Ptables;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel add;
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel delete;
    private javax.swing.JLabel help;
    private javax.swing.JLabel home;
    private javax.swing.JLabel ico2;
    private javax.swing.JLabel ico3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel signOut;
    private javax.swing.JLabel signOut4;
    private javax.swing.JLabel signout4;
    // End of variables declaration//GEN-END:variables
}