/**
 * La clase `Login` en Java es una aplicación GUI que permite a los usuarios iniciar sesión con un
 * nombre de usuario y contraseña, presentando elementos interactivos y animaciones.
 */
package login;
import AppPackage.AnimationClass;
import java.awt.Dimension;

import vistas.menus.MenuPrincipal;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

public class Login extends javax.swing.JFrame {

    
    private int posicionX = 0;
    private boolean estado = true;
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        userTxt.setFocusable(false); 
        PanelLogin.setVisible(false);
        //this.setUndecorated(true);
        
    }
    
    /*private class Der implements Runnable {
        @Override
        public void run() {
            while (true) {
                try {
                    Thread.sleep(10); // Ajusta la velocidad del movimiento
                    posicionX += 1; // Incrementa la posición en X

                    // Actualizar la posición del panel
                    jPanel2.setBounds(posicionX, jPanel2.getY(), jPanel2.getWidth(), jPanel2.getHeight());

                    // Reiniciar la posición si el panel sale de la ventana
                    if (posicionX >= 100) {
                        posicionX = 100;
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        }
    }*/
    
    /*private class Izq implements Runnable {
    @Override
    public void run() {
        while (true) {
            try {
                Thread.sleep(10); // Ajusta la velocidad del movimiento
                posicionX -= 1; // Decrementa la posición en X para mover hacia la izquierda

                // Actualizar la posición del panel
                PanelLogin.setBounds(posicionX, PanelLogin.getY(), PanelLogin.getWidth(), PanelLogin.getHeight());

                // Reiniciar la posición si el panel sale de la ventana
                if (posicionX <= 2000) {
                    posicionX = 1000;
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}*/
    
  /*Thread hiloMovimiento = new Thread(new MovimientoPanel());
    hiloMovimiento.start();*/

 
    
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        Inventory = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        Explore = new javax.swing.JLabel();
        about = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        IM1 = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        userTxt = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1361, 735));

        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Inventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setText("INVENTORY APP");
        back.add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clothing");
        back.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inventory");
        back.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        Login.setBackground(new java.awt.Color(0, 0, 0, 0));
        Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Login.setText("Login");
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login.setOpaque(true);
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginMouseExited(evt);
            }
        });
        back.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 2, 60, 40));

        Explore.setBackground(new java.awt.Color(0, 0, 0, 0));
        Explore.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Explore.setForeground(new java.awt.Color(255, 255, 255));
        Explore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Explore.setText("Explore");
        Explore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Explore.setOpaque(true);
        Explore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExploreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExploreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExploreMouseExited(evt);
            }
        });
        back.add(Explore, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 2, 70, 40));

        about.setBackground(new java.awt.Color(0, 0, 0, 0));
        about.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        about.setText("About");
        about.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about.setOpaque(true);
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutMouseExited(evt);
            }
        });
        back.add(about, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 2, 70, 40));

        home.setBackground(new java.awt.Color(0, 0, 0, 0));
        home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.setOpaque(true);
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeMouseExited(evt);
            }
        });
        back.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 2, 70, 40));

        IM1.setBackground(new java.awt.Color(42, 33, 133, 150));
        IM1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IM1.setForeground(new java.awt.Color(255, 255, 255));
        IM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IM1.setText("Inventory manager");
        IM1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IM1.setOpaque(true);
        IM1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IM1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IM1MouseExited(evt);
            }
        });
        back.add(IM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, 40));

        PanelLogin.setBackground(new java.awt.Color(0, 0, 0, 150));

        userTxt.setBackground(new java.awt.Color(50, 44, 43));
        userTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(153, 153, 153));
        userTxt.setText("Enter your username");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });

        login.setBackground(new java.awt.Color(153, 153, 255));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.setAlignmentY(0.0F);
        login.setBorder(null);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setFocusPainted(false);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        passTxt.setBackground(new java.awt.Color(50, 44, 43));
        passTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passTxt.setForeground(new java.awt.Color(102, 102, 102));
        passTxt.setText("*******");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login to your account");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGINWHITE.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eye.png"))); // NOI18N

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                        .addComponent(icon)
                        .addGap(113, 113, 113)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        back.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 180, 330, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/videito.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1370, 735));
        jLabel1.setPreferredSize(new java.awt.Dimension(1370, 735));
        back.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseEntered
        //AnimationClass menus = new AnimationClass();
        // menus.jLabelYUp(250, 220, 5, 10, iconUser);
    }//GEN-LAST:event_userTxtMouseEntered

    private void userTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseExited
        //AnimationClass menus = new AnimationClass();
        //menus.jLabelYDown(220, 250, 5, 10, iconUser);
    }//GEN-LAST:event_userTxtMouseExited

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        if (userTxt.getText().equals("Enter your username")) {
            userTxt.setText("");
            //userTxt.setForeground(Color.black);
            userTxt.setFocusable(true);
            userTxt.requestFocusInWindow();
        }
        if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("*******");
            //passTxt.setForeground(Color.gray);

        }
    }//GEN-LAST:event_userTxtMousePressed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(new java.awt.Color(42, 33, 133));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(new java.awt.Color(153,153,255));
    }//GEN-LAST:event_loginMouseExited

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        //System.out.println("Se presionó el botón login");
        LoginUsuarios log = new LoginUsuarios ();
        String user = userTxt.getText();
        String password = passTxt.getText();
        boolean verificarAdmin = log.verificarCredenciales(user, password);
        boolean verificarUsuario = false;
        try {
            int id = Integer.parseInt(user);
            verificarUsuario = log.verificarCredenciales(user, password);
        } catch (NumberFormatException e) {
            //System.out.println("El ID no es un número válido: " + user);
        }
        if (verificarAdmin || verificarUsuario) {
            setVisible(false);
            MenuPrincipal mp = new MenuPrincipal();
            mp.setVisible(true);
            String name = log.nombre;
            mp.LabersUser.setText("Hello, "+name);
            //mp.welcome.setText("Hello " + userTxt.getText());
        } else {
            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.", "Error de login", JOptionPane.ERROR_MESSAGE);
            userTxt.setText("");
            passTxt.setText("");
        }
    }//GEN-LAST:event_loginActionPerformed

    private void passTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseEntered
        //AnimationClass menus = new AnimationClass();
        //menus.jLabelYUp(330, 310, 5, 10, iconPass);
    }//GEN-LAST:event_passTxtMouseEntered

    private void passTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseExited
        //AnimationClass menus = new AnimationClass();
        //menus.jLabelYDown(310, 330, 5, 10, iconPass);
    }//GEN-LAST:event_passTxtMouseExited

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (String.valueOf(passTxt.getPassword()).equals("*******")) {
            passTxt.setText("");
            //passTxt.setForeground(Color.black);
            passTxt.setFocusable(true);
            passTxt.requestFocusInWindow();
        }
        if (userTxt.getText().isEmpty()) {
            userTxt.setText("Enter your username");
            //userTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passTxtMousePressed

    private void LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseEntered
        Login.setBackground(new java.awt.Color(0,0,0,150));
        Login.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LoginMouseEntered

    private void LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseExited
        Login.setBackground(new java.awt.Color(0,0,0,0));
        Login.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_LoginMouseExited

    private void IM1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IM1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_IM1MouseEntered

    private void IM1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IM1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_IM1MouseExited

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
       PanelLogin.setVisible(true);
    }//GEN-LAST:event_LoginMouseClicked

    private void ExploreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExploreMouseClicked
        // TODO add your h
    }//GEN-LAST:event_ExploreMouseClicked

    private void ExploreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExploreMouseEntered
        Explore.setBackground(new java.awt.Color(0,0,0,150));
        Explore.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_ExploreMouseEntered

    private void ExploreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExploreMouseExited
        Explore.setBackground(new java.awt.Color(0,0,0,0));
        Explore.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_ExploreMouseExited

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutMouseClicked

    private void aboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseEntered
        about.setBackground(new java.awt.Color(0,0,0,150));
        about.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_aboutMouseEntered

    private void aboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMouseExited
        about.setBackground(new java.awt.Color(0,0,0,0));
        about.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_aboutMouseExited

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homeMouseClicked

    private void homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseEntered
        home.setBackground(new java.awt.Color(0,0,0,150));
        home.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_homeMouseEntered

    private void homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseExited
        home.setBackground(new java.awt.Color(0,0,0,0));
        home.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_homeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        FlatLaf.registerCustomDefaultsSource("table");
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Explore;
    private javax.swing.JLabel IM1;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel Login;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JLabel about;
    private javax.swing.JPanel back;
    private javax.swing.JLabel home;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passTxt;
    public javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
