package login;
import AppPackage.AnimationClass;
import java.awt.Color;
import vistas.menus.MenuPrincipal;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form xs
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        userTxt.setFocusable(false); 
        //this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        About = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        About2 = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        IM = new javax.swing.JLabel();
        PanelLogin = new javax.swing.JPanel();
        userTxt = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        passTxt = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1370, 735));
        setResizable(false);
        setSize(new java.awt.Dimension(1361, 735));

        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setText("Home");
        back.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, -1));

        About.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        About.setForeground(new java.awt.Color(255, 255, 255));
        About.setText("Explore");
        back.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        Login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 255, 255));
        Login.setText("Login");
        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        back.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, -1, -1));

        About2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        About2.setForeground(new java.awt.Color(255, 255, 255));
        About2.setText("About");
        back.add(About2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, -1, -1));

        Inventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Inventory.setForeground(new java.awt.Color(255, 255, 255));
        Inventory.setText("INVENTORY APP");
        back.add(Inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Clothing");
        back.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Inventory");
        back.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        IM.setBackground(new java.awt.Color(42, 33, 133, 150));
        IM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IM.setForeground(new java.awt.Color(255, 255, 255));
        IM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IM.setText("Inventory manager");
        IM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IM.setOpaque(true);
        IM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IMMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IMMouseExited(evt);
            }
        });
        back.add(IM, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 180, 40));

        PanelLogin.setBackground(new java.awt.Color(0, 0, 0, 150));

        userTxt.setBackground(new java.awt.Color(50, 44, 43));
        userTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(153, 153, 153));
        userTxt.setText("Enter your username");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });

        login.setBackground(new java.awt.Color(153, 153, 255));
        login.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("LOGIN");
        login.setAlignmentY(0.0F);
        login.setBorder(null);
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.setFocusPainted(false);
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        passTxt.setBackground(new java.awt.Color(50, 44, 43));
        passTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        passTxt.setForeground(new java.awt.Color(102, 102, 102));
        passTxt.setText("*******");
        passTxt.setBorder(null);
        passTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                passTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                passTxtMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passTxtMousePressed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login to your account");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LOGINWHITE.png"))); // NOI18N

        javax.swing.GroupLayout PanelLoginLayout = new javax.swing.GroupLayout(PanelLogin);
        PanelLogin.setLayout(PanelLoginLayout);
        PanelLoginLayout.setHorizontalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                        .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addGroup(PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLoginLayout.createSequentialGroup()
                        .addComponent(icon)
                        .addGap(132, 132, 132))))
        );
        PanelLoginLayout.setVerticalGroup(
            PanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLoginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        back.add(PanelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 310, 370));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/videito.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1370, 735));
        jLabel1.setPreferredSize(new java.awt.Dimension(1370, 735));
        back.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseEntered
        //AnimationClass menus = new AnimationClass();
        // menus.jLabelYUp(250, 220, 5, 10, iconUser);
    }//GEN-LAST:event_userTxtMouseEntered

    private void userTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMouseExited
        //AnimationClass menus = new AnimationClass();
        //menus.jLabelYDown(220, 250, 5, 10, iconUser);
    }//GEN-LAST:event_userTxtMouseExited

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        if (userTxt.getText().equals("Enter your username")) {
            userTxt.setText("");
            //userTxt.setForeground(Color.black);
            userTxt.setFocusable(true);
            userTxt.requestFocusInWindow();
        }
        if (String.valueOf(passTxt.getPassword()).isEmpty()) {
            passTxt.setText("*******");
            //passTxt.setForeground(Color.gray);

        }
    }//GEN-LAST:event_userTxtMousePressed

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(new java.awt.Color(42, 33, 133));
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(new java.awt.Color(153,153,255));
    }//GEN-LAST:event_loginMouseExited

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        System.out.println("Se presionó el botón login");
        usersLogin log = new usersLogin ();
        System.out.println(userTxt.getText()+passTxt.getText());
        boolean verificar = log.ingresoAdmin(userTxt.getText(), passTxt.getText());
        if(verificar == true)
        {
            setVisible(false);
            MenuPrincipal mp = new MenuPrincipal();
            mp.setVisible(true);
            //mp.welcome.setText("Hello "+userTxt.getText());
        }else{
            userTxt.setText("Enter your username");
            passTxt.setText("*******");

        }
    }//GEN-LAST:event_loginActionPerformed

    private void passTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseEntered
        //AnimationClass menus = new AnimationClass();
        //menus.jLabelYUp(330, 310, 5, 10, iconPass);
    }//GEN-LAST:event_passTxtMouseEntered

    private void passTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMouseExited
        //AnimationClass menus = new AnimationClass();
        //menus.jLabelYDown(310, 330, 5, 10, iconPass);
    }//GEN-LAST:event_passTxtMouseExited

    private void passTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passTxtMousePressed
        if (String.valueOf(passTxt.getPassword()).equals("*******")) {
            passTxt.setText("");
            //passTxt.setForeground(Color.black);
            passTxt.setFocusable(true);
            passTxt.requestFocusInWindow();
        }
        if (userTxt.getText().isEmpty()) {
            userTxt.setText("Enter your username");
            //userTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_passTxtMousePressed

    private void IMMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMMouseEntered
        IM.setBackground(new java.awt.Color(255,255,255));
        IM.setForeground(new java.awt.Color(42,33,133));
    }//GEN-LAST:event_IMMouseEntered

    private void IMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IMMouseExited
        IM.setBackground(new java.awt.Color(42,33,133));
        IM.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_IMMouseExited

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        AnimationClass menus = new AnimationClass();
        menus.jLabelXLeft(250, 220, 5, 10, icon);
    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        FlatLaf.registerCustomDefaultsSource("table");
        FlatMacDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About;
    private javax.swing.JLabel About2;
    private javax.swing.JLabel Home;
    private javax.swing.JLabel IM;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel Login;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPanel back;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passTxt;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
